import { FieldConfig, FieldWidth } from '@/components/DynamicForm/DynamicForm';

export const registrationFormConfig: FieldConfig[] = [
  { name: 'title', label: 'Create Your Agency Account', type: 'label', tag: 'h2', children: null },
  {
    name: 'subTitle',
    label: 'Start your journey with TravelNinja today',
    type: 'label',
    tag: 'h3',
  },
  {
    name: 'fullName',
    label: 'Full Name',
    type: 'input',
    placeholder: 'Enter full name',
    required: true,
    width: FieldWidth.HALF,
  },
  {
    name: 'agencyName',
    label: 'Agency Name',
    type: 'input',
    placeholder: 'Enter agency name',
    width: FieldWidth.HALF,
  },
  {
    name: 'email',
    label: 'Email Address',
    type: 'input',
    required: true,
    placeholder: 'Enter email address',
    width: FieldWidth.HALF,
  },
  {
    name: 'website',
    label: 'Website(optional)',
    type: 'input',
    placeholder: 'https://yourwebsite.com',
    width: FieldWidth.HALF,
  },
  {
    name: 'address',
    label: 'Address',
    type: 'input',
    placeholder: 'Enter full address',
    required: true,
    width: FieldWidth.FULL,
  },
  {
    name: 'city',
    label: 'City',
    type: 'input',
    placeholder: 'Enter city',
    required: true,
    width: FieldWidth.THIRD,
  },
  {
    name: 'state',
    label: 'State',
    type: 'input',
    placeholder: 'Enter State',
    required: true,
    width: FieldWidth.THIRD,
  },
  {
    name: 'postCode',
    label: 'Post Code',
    type: 'input',
    placeholder: 'Enter post code',
    required: true,
    width: FieldWidth.THIRD,
  },
  {
    name: 'password',
    label: 'Password',
    type: 'input',
    placeholder: 'Create a password',
    required: true,
    width: FieldWidth.HALF,
  },
  {
    name: 'confirmPassword',
    label: 'Confirm Password',
    type: 'input',
    placeholder: 'Confirm your password',
    required: true,
    width: FieldWidth.HALF,
  },
];
