import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import './styleguide.css';
import { NotificationProvider } from '@/providers/NotificationProvider';

const inter = Inter({
  subsets: ['latin'],
  weight: ['300', '500', '600', '700'], // Add only needed weights
  variable: '--font-inter',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={inter.variable}>
      <body>
        <NotificationProvider>{children}</NotificationProvider>
      </body>
    </html>
  );
}
