name: Build and Push Docker Image

on:
  push:
    branches:
      - main  # Run only when pushing to main

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Extract short commit SHA
        id: vars
        run: echo "SHA_SHORT=$(echo $GITHUB_SHA | cut -c1-7)" >> $GITHUB_ENV

      - name: Build Docker image with multiple tags
        run: |
          docker build \
            -t myorg/my-next-app:latest \
            -t myorg/my-next-app:${{ env.SHA_SHORT }} .

      - name: Push both tags
        run: |
          docker push myorg/my-next-app:latest
          docker push myorg/my-next-app:${{ env.SHA_SHORT }}
